title: Alex Blog

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "default"

markdown: kramdown

kramdown:
  input: GFM

paginate: 5
paginate_path: /page:num/

header_pages:
  - about.md
  - it-support/index.md
  - cloud-devops/index.md
  - bodybuilding/index.md
  - journey/index.md
